{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-add-funds-flow",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-add-funds-flow-1.0.0-alpha.aar",
          "url": "feature-add-funds-flow-1.0.0-alpha.aar",
          "size": 216203,
          "sha512": "c3afa32e6c300d9c04e81919b422831072d1385797ad3e43a6a42771dd1a5c1b1eb10a7de53983acb0e723d12051b19fb89f29d8a3a9b0411c3aebaa27eec2b3",
          "sha256": "1f861f80a250a6491cf070ef22fb8a3ed43ff41f06c2fb26c45faa776cc9f66b",
          "sha1": "eb3c23bf0d8453748de8ae4775d922b46c70e52c",
          "md5": "b34384c0d23b91568960e03029302f90"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-sardine-sdk",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-add-funds-flow-1.0.0-alpha.aar",
          "url": "feature-add-funds-flow-1.0.0-alpha.aar",
          "size": 216203,
          "sha512": "c3afa32e6c300d9c04e81919b422831072d1385797ad3e43a6a42771dd1a5c1b1eb10a7de53983acb0e723d12051b19fb89f29d8a3a9b0411c3aebaa27eec2b3",
          "sha256": "1f861f80a250a6491cf070ef22fb8a3ed43ff41f06c2fb26c45faa776cc9f66b",
          "sha1": "eb3c23bf0d8453748de8ae4775d922b46c70e52c",
          "md5": "b34384c0d23b91568960e03029302f90"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-add-funds-flow-1.0.0-alpha-sources.jar",
          "url": "feature-add-funds-flow-1.0.0-alpha-sources.jar",
          "size": 17179,
          "sha512": "ed56be3a514c0ec904c3db5ecbc6b2763f627dbe6c403f219af3540fd605d17fe225e5884d38a1d51b5d2457aa742aee84f71e2ff0f42e4d44ae2d155c9924e3",
          "sha256": "c3e2f991cb56bfef159af43fbe00b6669c9b4c13d843b138623a7163e61021bb",
          "sha1": "006344455c21e5de6500e6030bdc14647c4c47d9",
          "md5": "f5fec680972de9343a732059ab16559a"
        }
      ]
    }
  ]
}
