{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-sardine-sdk",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-sardine-sdk-1.0.0-alpha.aar",
          "url": "core-sardine-sdk-1.0.0-alpha.aar",
          "size": 7397,
          "sha512": "230b969533756942405c64903e9c7d447939595b89d7b325b056842950a0a54ff0c6a3c7a7be16801e2b8435d1908dea5d7c9861f71be1ade30d49375e199d35",
          "sha256": "12962b844d7f16389674acd46d7ba6e3cb25655024a826b10df42c37eb0de157",
          "sha1": "2c5c59fd70f4910bb93a3e210495147ee46cb5fc",
          "md5": "e7722dec5b50b254db2a358185359d73"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-sardine-sdk-library",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-sardine-sdk-1.0.0-alpha.aar",
          "url": "core-sardine-sdk-1.0.0-alpha.aar",
          "size": 7397,
          "sha512": "230b969533756942405c64903e9c7d447939595b89d7b325b056842950a0a54ff0c6a3c7a7be16801e2b8435d1908dea5d7c9861f71be1ade30d49375e199d35",
          "sha256": "12962b844d7f16389674acd46d7ba6e3cb25655024a826b10df42c37eb0de157",
          "sha1": "2c5c59fd70f4910bb93a3e210495147ee46cb5fc",
          "md5": "e7722dec5b50b254db2a358185359d73"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-sardine-sdk-1.0.0-alpha-sources.jar",
          "url": "core-sardine-sdk-1.0.0-alpha-sources.jar",
          "size": 4129,
          "sha512": "bbb2ec3b0f19f9d82464a158ac7c4f7dc2e4bd1f58a28794a1c25fb329ddfd30947d3d137a80eadca2d61e41ebf10b020d5c2da4e1c713f9a28ea76158d11cbd",
          "sha256": "5d6742f31196f4299f9c215d059483f607c3f0f51120bf6b10565e31614b3984",
          "sha1": "8bd03dae88cc59a8d5bc4c27719da6b0a3fd473e",
          "md5": "8c9b3be8a76429b61218d44b15984f41"
        }
      ]
    }
  ]
}
