{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-create-sports-contest-flow",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-create-sports-contest-flow-1.0.0-alpha.aar",
          "url": "feature-create-sports-contest-flow-1.0.0-alpha.aar",
          "size": 561369,
          "sha512": "4d8dfff676ebd1bd0533f8cafd27cb3356b1001b050aca5962a70810534163e560ac87ffff5e870496665f69e68a92205b6d5ff60a16d9516909c081cb470738",
          "sha256": "b870c9fc15dacbcda93791a7e7750640c283b6e6f38e953cae0fb0a20b558881",
          "sha1": "0dd68705e0432fa30d036bce81052b8dc41da047",
          "md5": "cc7eaf34cf5b2368a22dcf05a99af551"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-create-sports-contest-flow-1.0.0-alpha.aar",
          "url": "feature-create-sports-contest-flow-1.0.0-alpha.aar",
          "size": 561369,
          "sha512": "4d8dfff676ebd1bd0533f8cafd27cb3356b1001b050aca5962a70810534163e560ac87ffff5e870496665f69e68a92205b6d5ff60a16d9516909c081cb470738",
          "sha256": "b870c9fc15dacbcda93791a7e7750640c283b6e6f38e953cae0fb0a20b558881",
          "sha1": "0dd68705e0432fa30d036bce81052b8dc41da047",
          "md5": "cc7eaf34cf5b2368a22dcf05a99af551"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-create-sports-contest-flow-1.0.0-alpha-sources.jar",
          "url": "feature-create-sports-contest-flow-1.0.0-alpha-sources.jar",
          "size": 37291,
          "sha512": "1449e88c47fbd933f8b5f68dc1a600a996b121eecb75e9f8e6b9699fa7ca812cb9654379404bb76dd4ac9c4c149416b169953b1092a26466bcf20e0f153b76ab",
          "sha256": "3d36e1cdbf5ba64ad2a6d6c3272ad62d6ef3ee5721a35b188e7a83b582438d82",
          "sha1": "225b8eca0b61233ec9514b7d56dcf2587181c0cb",
          "md5": "1adbd5b3b29880b1e787a4f077de6f34"
        }
      ]
    }
  ]
}
