{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-credit-card-encryption",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-credit-card-encryption-1.0.0-alpha.aar",
          "url": "core-credit-card-encryption-1.0.0-alpha.aar",
          "size": 4730,
          "sha512": "6227c7fad82adac6b4302cd2f5105492eb997b372710fc7567235a026ed22cf1ffe85be9adee7139ffd53e770d0d8fbe0417a2ddb866031c097f269ea3fa5431",
          "sha256": "4e1fc5b116b165ad6c096be5c4d3a15d7edb69f7aba49eca5b836bda7fc5b197",
          "sha1": "1bfed1af8bb3b2afa1973bb89196ad7de0fb2f20",
          "md5": "486c17d126e44f3ddb062f412161125d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-payment-gateway-library",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-credit-card-encryption-1.0.0-alpha.aar",
          "url": "core-credit-card-encryption-1.0.0-alpha.aar",
          "size": 4730,
          "sha512": "6227c7fad82adac6b4302cd2f5105492eb997b372710fc7567235a026ed22cf1ffe85be9adee7139ffd53e770d0d8fbe0417a2ddb866031c097f269ea3fa5431",
          "sha256": "4e1fc5b116b165ad6c096be5c4d3a15d7edb69f7aba49eca5b836bda7fc5b197",
          "sha1": "1bfed1af8bb3b2afa1973bb89196ad7de0fb2f20",
          "md5": "486c17d126e44f3ddb062f412161125d"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-credit-card-encryption-1.0.0-alpha-sources.jar",
          "url": "core-credit-card-encryption-1.0.0-alpha-sources.jar",
          "size": 3386,
          "sha512": "35189148dd74d53c40c4f91e677ae306be72fcbd130bb76c841207cf0bac2c94f9adf086904c08d8323bcf869ff7d038d9b2756183dbcf23632bd8208d920a9f",
          "sha256": "4c4243ffd2fdf6f1e909beca4729d7c5bf3919fc7c5f8e1020fc3052ab9ba087",
          "sha1": "4a10003333d7d6a90a95f37451f3afe77289efb5",
          "md5": "67a7f491facdb180c349b1fa62ccd22e"
        }
      ]
    }
  ]
}
