{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-contest-details",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-contest-details-1.0.0-alpha.aar",
          "url": "feature-contest-details-1.0.0-alpha.aar",
          "size": 181909,
          "sha512": "ee6b9827ce42475cb5b4a8ef50abd3d27c40c72a9498d0d78978a1dfb86a846f8c6838af9763d768ef3bf92ed473b3faa095e20c0a2e52d4c8d7db1eec892463",
          "sha256": "b9ebcad4a608f1af1ba21d26a3226efb4a5032f6769ff3b37a66a8456dba4480",
          "sha1": "14e93bd5b0ed137e5694d33178cb05c7fe9bf1d7",
          "md5": "5825d0191e14ccf688eef485b0da311e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-contest-details-1.0.0-alpha.aar",
          "url": "feature-contest-details-1.0.0-alpha.aar",
          "size": 181909,
          "sha512": "ee6b9827ce42475cb5b4a8ef50abd3d27c40c72a9498d0d78978a1dfb86a846f8c6838af9763d768ef3bf92ed473b3faa095e20c0a2e52d4c8d7db1eec892463",
          "sha256": "b9ebcad4a608f1af1ba21d26a3226efb4a5032f6769ff3b37a66a8456dba4480",
          "sha1": "14e93bd5b0ed137e5694d33178cb05c7fe9bf1d7",
          "md5": "5825d0191e14ccf688eef485b0da311e"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-contest-details-1.0.0-alpha-sources.jar",
          "url": "feature-contest-details-1.0.0-alpha-sources.jar",
          "size": 15291,
          "sha512": "a55d040ba12ce31330d237cff961f807d0e76bc3cdba1c6298c59299a808c950c2434bd1f2054fb3abfc911fd71dfdae5fe8c8ee73830215240ca30a17e8122a",
          "sha256": "8417a58fe59185675afac0aa4c4b5622139f45f6f446e2908c4da8eaac743ed9",
          "sha1": "59607cf90d3f8b30befd5fa09de16c644470f12f",
          "md5": "33ba25d6ca91849b265d83e587d181f0"
        }
      ]
    }
  ]
}
