{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-ssn-form",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-ssn-form-1.0.0-alpha.aar",
          "url": "feature-ssn-form-1.0.0-alpha.aar",
          "size": 66160,
          "sha512": "62d635284f9f2669374a6b37a7c6cafc74b9a3f111da62e75dab46f211dd71cf90d7ad8cac0768621ffd13fa8e4517af5b6f7a7380d6b2a31a8f2d3e4be857e9",
          "sha256": "dde8c62a3effeb4448e6368a85889ad8e8cc6d691f9b1f87d4d7c3aa8979706f",
          "sha1": "1dc88ea41b14031a207ccd4c24b34bfe657794c7",
          "md5": "590c8a354bf8dfd2ca6d61bd003d488a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-ssn-form-1.0.0-alpha.aar",
          "url": "feature-ssn-form-1.0.0-alpha.aar",
          "size": 66160,
          "sha512": "62d635284f9f2669374a6b37a7c6cafc74b9a3f111da62e75dab46f211dd71cf90d7ad8cac0768621ffd13fa8e4517af5b6f7a7380d6b2a31a8f2d3e4be857e9",
          "sha256": "dde8c62a3effeb4448e6368a85889ad8e8cc6d691f9b1f87d4d7c3aa8979706f",
          "sha1": "1dc88ea41b14031a207ccd4c24b34bfe657794c7",
          "md5": "590c8a354bf8dfd2ca6d61bd003d488a"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-ssn-form-1.0.0-alpha-sources.jar",
          "url": "feature-ssn-form-1.0.0-alpha-sources.jar",
          "size": 8580,
          "sha512": "84b4e7342451558506321d4edd16fbe6803bbad0e3a2a6bc048e5227901ab8bee32d763200ad51b1267f307fb557bc2162020dad9de2c86487089c19271d01b0",
          "sha256": "e58f35aff90228583be3678a49dd3ebeff23abd031ddb0e72c5c00b66abf430c",
          "sha1": "d17bcd78fe81ffb583bdd76e8452f9d0aa04616e",
          "md5": "0871962993ae05d7169de4fc88abe0d2"
        }
      ]
    }
  ]
}
