{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-apollo",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-apollo-1.0.0-alpha.aar",
          "url": "core-apollo-1.0.0-alpha.aar",
          "size": 6948112,
          "sha512": "175d847650ca2de7db03a371b6e3e69a0b8312004870c25aff61c934e025f41edd7839a2a9aecb72be9f01e936843ee01c057e495987fd7a6880484e79d136a4",
          "sha256": "a90474f97d87b7dd73f086add220fc5bd0cd35b80e43e32dc55bfad56fefd25e",
          "sha1": "6a9d0ba6d518f438486fcea0f94f8379757845f2",
          "md5": "a2ceb829aefb588342f9bce056d133a5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-apollo-1.0.0-alpha.aar",
          "url": "core-apollo-1.0.0-alpha.aar",
          "size": 6948112,
          "sha512": "175d847650ca2de7db03a371b6e3e69a0b8312004870c25aff61c934e025f41edd7839a2a9aecb72be9f01e936843ee01c057e495987fd7a6880484e79d136a4",
          "sha256": "a90474f97d87b7dd73f086add220fc5bd0cd35b80e43e32dc55bfad56fefd25e",
          "sha1": "6a9d0ba6d518f438486fcea0f94f8379757845f2",
          "md5": "a2ceb829aefb588342f9bce056d133a5"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-apollo-1.0.0-alpha-sources.jar",
          "url": "core-apollo-1.0.0-alpha-sources.jar",
          "size": 16393,
          "sha512": "0cc42170ad5dd7506212c65b1a88adc6f2e43a95db3d3d76361795b8117efeb1aac298523b9c0610d6fc5a88f730155f0da3a25a67f451c3b67777615b66dbbe",
          "sha256": "89043fe01a2ba48c3ae56d36c50c178356f17a5c23dcb376497d0a322f9f069c",
          "sha1": "d335401bf5112b682601d8f7140576fa16e12030",
          "md5": "9a42cb27549624dea736507f051be422"
        }
      ]
    }
  ]
}
