{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "sdk-core",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-sardine-sdk",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.0.0-alpha.aar",
          "url": "sdk-core-1.0.0-alpha.aar",
          "size": 38391,
          "sha512": "79dc16405d9c36d8679420340e5ccf7033c4fdcdf82827aaf9b43de0e47dbb97ece715fe9c2f6f890db99bb10a421503f767134c980c50f51757fb1b528a4475",
          "sha256": "47be29b2cb0b304bc89118922a01badd5b801ad2d832522b67a230a77d0e1f66",
          "sha1": "b3bab19d227e90cc6b82a6d90b31cc8ef5851f42",
          "md5": "42beb87cb0a4b65def9d34a1de37f733"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-credit-card-encryption",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-sardine-sdk",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.0.0-alpha.aar",
          "url": "sdk-core-1.0.0-alpha.aar",
          "size": 38391,
          "sha512": "79dc16405d9c36d8679420340e5ccf7033c4fdcdf82827aaf9b43de0e47dbb97ece715fe9c2f6f890db99bb10a421503f767134c980c50f51757fb1b528a4475",
          "sha256": "47be29b2cb0b304bc89118922a01badd5b801ad2d832522b67a230a77d0e1f66",
          "sha1": "b3bab19d227e90cc6b82a6d90b31cc8ef5851f42",
          "md5": "42beb87cb0a4b65def9d34a1de37f733"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-core-1.0.0-alpha-sources.jar",
          "url": "sdk-core-1.0.0-alpha-sources.jar",
          "size": 14497,
          "sha512": "39c90c3cad98aed885eda5f4a862f86198cffe23c622ee1d8afbe1905e41b9f0ef780a7b32205dccb28b4f0de1300326617ee18e8bc9ec0e31d70143187b1a13",
          "sha256": "bcaf748aea90305d1244d11284a22d6e1be19bc7d54c1a5cd617462ea2a58246",
          "sha1": "bc190b777f8aaa23d2b72f583163c133ff51e193",
          "md5": "2742013d932769f1ccc24355b1462163"
        }
      ]
    }
  ]
}
