{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-login-flow",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-login-flow-1.0.0-alpha.aar",
          "url": "feature-login-flow-1.0.0-alpha.aar",
          "size": 1019186,
          "sha512": "7df2820cb56cd4b1137891df0bc74185abd9da9fbb55b8323072ab3585590f59429525e16fe8629fa1cf1b51ce1c69427100a607f5e8bacc2fb4d610fbdc6f76",
          "sha256": "07dafb834f6131dcf93d57cbb45d40f81fc846283534fd877de31003013663a0",
          "sha1": "dc1b04a1d7300d62c213bf8612e2d9353b815611",
          "md5": "8dff2f5820ff7cc865376b03bc9ba5e2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-webview",
          "version": {
            "requires": "0.27.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-login-flow-1.0.0-alpha.aar",
          "url": "feature-login-flow-1.0.0-alpha.aar",
          "size": 1019186,
          "sha512": "7df2820cb56cd4b1137891df0bc74185abd9da9fbb55b8323072ab3585590f59429525e16fe8629fa1cf1b51ce1c69427100a607f5e8bacc2fb4d610fbdc6f76",
          "sha256": "07dafb834f6131dcf93d57cbb45d40f81fc846283534fd877de31003013663a0",
          "sha1": "dc1b04a1d7300d62c213bf8612e2d9353b815611",
          "md5": "8dff2f5820ff7cc865376b03bc9ba5e2"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-login-flow-1.0.0-alpha-sources.jar",
          "url": "feature-login-flow-1.0.0-alpha-sources.jar",
          "size": 75634,
          "sha512": "88581940b26772919200463ee1f2228fc067cb0ab5e95d19840a2d8db75845cce69ec2cb9e9d76535c5e541ea3320a9cb407f74d1d5483cb6952a6caae07b51d",
          "sha256": "627da051a8c88d5bfb12821e9e812f7cb77351ac9c066327000906b5553f1235",
          "sha1": "7e6f04dd27e0dd3be07e1b982ff4623b4b68e2de",
          "md5": "6177b2f185ba9de4393d5a5f032cc4dd"
        }
      ]
    }
  ]
}
