{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-promo",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-promo-1.0.0-alpha.aar",
          "url": "feature-promo-1.0.0-alpha.aar",
          "size": 109655,
          "sha512": "c30e456459ceb3a4abc720220e6a19211f00d677588707dfabdfe660eab296ca5df76e104a536c80671d7ec1184a495735a9e87748f033371422e1c1e602ac8f",
          "sha256": "95b16b397a1acee64f5dd5cd3d573449d1f42e2ce0e99d3fc3712ca5ecdd3621",
          "sha1": "5bae364568e689a6380bb5114e353e9269f98e22",
          "md5": "9797a44bf3f74edcaa135de18e547cc5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-promo-1.0.0-alpha.aar",
          "url": "feature-promo-1.0.0-alpha.aar",
          "size": 109655,
          "sha512": "c30e456459ceb3a4abc720220e6a19211f00d677588707dfabdfe660eab296ca5df76e104a536c80671d7ec1184a495735a9e87748f033371422e1c1e602ac8f",
          "sha256": "95b16b397a1acee64f5dd5cd3d573449d1f42e2ce0e99d3fc3712ca5ecdd3621",
          "sha1": "5bae364568e689a6380bb5114e353e9269f98e22",
          "md5": "9797a44bf3f74edcaa135de18e547cc5"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-promo-1.0.0-alpha-sources.jar",
          "url": "feature-promo-1.0.0-alpha-sources.jar",
          "size": 9705,
          "sha512": "301099bd4048937f4b9bd4aeda0d47f27dcde51362f569584c647b2d4786bd769ce9c19addac6c267b680505e87822124ed1d3135cc96eeaaf6c4d258fdf451b",
          "sha256": "6d5ad6a9f5d61eb55b34809860b8b64fcb43a891cb58f47fcb58343a4b4adecf",
          "sha1": "99f686650ebe66268fe9099f4282d8d27f708b44",
          "md5": "3d8923cc49d252fbed5313feb2be6a36"
        }
      ]
    }
  ]
}
