{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-logger",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-1.0.0-alpha.aar",
          "url": "core-logger-1.0.0-alpha.aar",
          "size": 111094,
          "sha512": "164374185f12498cb7357c0a358daea1bd47331da0b58ce5efdf9bd8c93fa2779ba11e66d12e3ceded7b646338e2fc3a0d353778facaf7910c242123a5d11c65",
          "sha256": "2738675c2cfa37b9c304ab4ab374efa84c978a9da0f57984aeecdca907696913",
          "sha1": "b1afef44574c757ae5f4393a6619cf78d9e3a684",
          "md5": "9ad8159d7f5ad5fb6c103016c617ca18"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "segment-android-integration",
          "version": {
            "requires": "6.8.2"
          }
        },
        {
          "group": "com.segment.analytics.android",
          "module": "analytics",
          "version": {
            "requires": "4.11.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "23.1.1"
          }
        },
        {
          "group": "com.iterable",
          "module": "iterableapi",
          "version": {
            "requires": "3.4.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-logger-1.0.0-alpha.aar",
          "url": "core-logger-1.0.0-alpha.aar",
          "size": 111094,
          "sha512": "164374185f12498cb7357c0a358daea1bd47331da0b58ce5efdf9bd8c93fa2779ba11e66d12e3ceded7b646338e2fc3a0d353778facaf7910c242123a5d11c65",
          "sha256": "2738675c2cfa37b9c304ab4ab374efa84c978a9da0f57984aeecdca907696913",
          "sha1": "b1afef44574c757ae5f4393a6619cf78d9e3a684",
          "md5": "9ad8159d7f5ad5fb6c103016c617ca18"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-logger-1.0.0-alpha-sources.jar",
          "url": "core-logger-1.0.0-alpha-sources.jar",
          "size": 14840,
          "sha512": "a6d9608561115e890ebfcb7d3f912ec6a46d80f38ca30fdf08aff9eae3173116fa50d4174af377b2f8306de0a296c6f8617604960a1b838819589ecaee7d9ecd",
          "sha256": "2db4256f0c87c36092ef573a5269eacb65b22e4a5385216c6d84be2c4ca190e2",
          "sha1": "ac00f8d426137469ab2d160510be4410d9cf2406",
          "md5": "7c011668a5046c2562e1191690bbb664"
        }
      ]
    }
  ]
}
