ENV['RCT_NEW_ARCH_ENABLED'] = '0'

source 'https://github.com/Lucra-Sports/lucra-ios-sdk.git'
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 15.1
prepare_react_native_project!

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'LucrasdkExample' do
  config = use_native_modules!
  
  pod "Resolver", :git => "https://github.com/ospfranco/Resolver.git", :branch => "master"
  
  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true,
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )
  end
end
