{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-common",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-common-1.0.0-alpha.aar",
          "url": "core-common-1.0.0-alpha.aar",
          "size": 58015,
          "sha512": "1ecea7db664f41966c97e46dce71b6dcc1ea2314c23abf841768e8872aa5ed6ed9dda5e0fca03599d76ea5244c7ccdfd06525141e951c41d5a3084607deb2e98",
          "sha256": "6649ee145e3d24c0c7e3e594360526a39b76ac9d32195b33c2c12667223b3007",
          "sha1": "3f15f435ec1ddbb8c483a4849155418658e0582a",
          "md5": "b404ceb245ef042e252f62b3c5538a7f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-common-1.0.0-alpha.aar",
          "url": "core-common-1.0.0-alpha.aar",
          "size": 58015,
          "sha512": "1ecea7db664f41966c97e46dce71b6dcc1ea2314c23abf841768e8872aa5ed6ed9dda5e0fca03599d76ea5244c7ccdfd06525141e951c41d5a3084607deb2e98",
          "sha256": "6649ee145e3d24c0c7e3e594360526a39b76ac9d32195b33c2c12667223b3007",
          "sha1": "3f15f435ec1ddbb8c483a4849155418658e0582a",
          "md5": "b404ceb245ef042e252f62b3c5538a7f"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-common-1.0.0-alpha-sources.jar",
          "url": "core-common-1.0.0-alpha-sources.jar",
          "size": 9468,
          "sha512": "5bac5d795e29f7fb3c7c95b392042769518b721dd1b3ac3d961bd489c1528a43314db3dea2131dea4db8f0651d8df9a16e4951fd1f5f7ea9266c618f4d4aaaac",
          "sha256": "740f3051f92d8dbf47da9e50dab0182c26d0fd8ca79d6a24a0ce3cfa9e74e02d",
          "sha1": "04583bc007702494b5804057e7708a0df9745ab7",
          "md5": "05faea38a7d631a2208b3d2eae77af5e"
        }
      ]
    }
  ]
}
