{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-my-contests",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-my-contests-1.0.0-alpha.aar",
          "url": "feature-my-contests-1.0.0-alpha.aar",
          "size": 145166,
          "sha512": "4195d5542d62014a1775b95121b0c4f4968c99ff5141434210b2e311af623f12763adfdf4fe1b104f75457d2b48d3d0fa6e5ad13a69dc2d49155357cdb00ba40",
          "sha256": "09052a656a367b881a19e53fa3a25aaff49982fbee57562e9810a731f7de2d09",
          "sha1": "eab65fd4a66520ae2da287eb0e6903cf8c55eb5f",
          "md5": "6059f0ff0fa86f5fa8c3ed80107b188e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-base-contest-list-components",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-my-contests-1.0.0-alpha.aar",
          "url": "feature-my-contests-1.0.0-alpha.aar",
          "size": 145166,
          "sha512": "4195d5542d62014a1775b95121b0c4f4968c99ff5141434210b2e311af623f12763adfdf4fe1b104f75457d2b48d3d0fa6e5ad13a69dc2d49155357cdb00ba40",
          "sha256": "09052a656a367b881a19e53fa3a25aaff49982fbee57562e9810a731f7de2d09",
          "sha1": "eab65fd4a66520ae2da287eb0e6903cf8c55eb5f",
          "md5": "6059f0ff0fa86f5fa8c3ed80107b188e"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-my-contests-1.0.0-alpha-sources.jar",
          "url": "feature-my-contests-1.0.0-alpha-sources.jar",
          "size": 11276,
          "sha512": "08267de8aef7d406ec15a18e559f9e332fc064c8f422a4ad6578158b797f27cc5db8d3cd272cb510e15cfac0b5c792d2bc5c8acd2eaeb713f87fb4900fc9ec4b",
          "sha256": "f827f4d60d3474d99722836b491a337579dfce4abe788e86730920c17b8595a7",
          "sha1": "d15147675e07152387909083c8aa143d3eb8c9af",
          "md5": "4a897910b2441a191da16bafbb4b634e"
        }
      ]
    }
  ]
}
