
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.lucrasdk;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeLucraClientSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "LucraClient";

  public NativeLucraClientSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void initialize(ReadableMap options, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void present(String flow);

  @ReactMethod
  @DoNotStrip
  public abstract void createGamesMatchup(String gameTypeId, double wagerAmount, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void acceptGamesMatchup(String matchupId, String teamId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void cancelGamesMatchup(String matchupId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getGamesMatchup(String matchupId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void configureUser(ReadableMap user, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void logout(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getUser(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getSportsMatchup(String contestId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventType);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
