{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-social",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-social-1.0.0-alpha.aar",
          "url": "feature-social-1.0.0-alpha.aar",
          "size": 265284,
          "sha512": "cf6fff3f30ccb851d3724f9364540d5037c4a3fae2f68acc0a4cb8cc0e333b521a635470037a7b61c9348e00a4a25707ab671efeaf93f57eee03e112f165df79",
          "sha256": "d2911d44815365a67bea108307498a6aef580e1e1f45160649d8eed0207ae3d5",
          "sha1": "a4fbedd6678970b517fad10050f38bd48ac77723",
          "md5": "92b38e9ed021f2e14565c9b315a53c2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-social-1.0.0-alpha.aar",
          "url": "feature-social-1.0.0-alpha.aar",
          "size": 265284,
          "sha512": "cf6fff3f30ccb851d3724f9364540d5037c4a3fae2f68acc0a4cb8cc0e333b521a635470037a7b61c9348e00a4a25707ab671efeaf93f57eee03e112f165df79",
          "sha256": "d2911d44815365a67bea108307498a6aef580e1e1f45160649d8eed0207ae3d5",
          "sha1": "a4fbedd6678970b517fad10050f38bd48ac77723",
          "md5": "92b38e9ed021f2e14565c9b315a53c2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-social-1.0.0-alpha-sources.jar",
          "url": "feature-social-1.0.0-alpha-sources.jar",
          "size": 19164,
          "sha512": "1c079a9e09a56b282c42a2c2b533f4a531f2910366fdf2eb75669c081d6f5df6a29f6e8ae8f9ef97a453e55c5b90dad521e0f9a96460a757fa0fd57f4d424a83",
          "sha256": "58c698f6aa0583602c799cbc865fb4a3911fdcaf136b8cdb8aaf10c5440858e6",
          "sha1": "870ffa24b31838231dbbc27d7aa35e663347b6f6",
          "md5": "d25ebfe21f65802f6b1039e6bbd6d10a"
        }
      ]
    }
  ]
}
