{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-mega-menu",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-mega-menu-1.0.0-alpha.aar",
          "url": "feature-mega-menu-1.0.0-alpha.aar",
          "size": 53801,
          "sha512": "5e8930bbe65b80a148c51fff112533886cc4f6bcead4b640471d4d2694da106087bf49cfccb4c525c32d93d7e26804f82064157379a3d789e65767156b5bd83a",
          "sha256": "b2f4e7c3445de5f74fae346711ffb4068a17f81601716052105208d21bff8f91",
          "sha1": "f3652ee4e20a32eb1e7ccf46895a8d58fe1a984a",
          "md5": "650b2a7acc2248b048eb51e917d1384c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-add-funds-flow",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-promo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-home-landing",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-ssn-form",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-account-detail",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-mega-menu-1.0.0-alpha.aar",
          "url": "feature-mega-menu-1.0.0-alpha.aar",
          "size": 53801,
          "sha512": "5e8930bbe65b80a148c51fff112533886cc4f6bcead4b640471d4d2694da106087bf49cfccb4c525c32d93d7e26804f82064157379a3d789e65767156b5bd83a",
          "sha256": "b2f4e7c3445de5f74fae346711ffb4068a17f81601716052105208d21bff8f91",
          "sha1": "f3652ee4e20a32eb1e7ccf46895a8d58fe1a984a",
          "md5": "650b2a7acc2248b048eb51e917d1384c"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-mega-menu-1.0.0-alpha-sources.jar",
          "url": "feature-mega-menu-1.0.0-alpha-sources.jar",
          "size": 4068,
          "sha512": "203ded7ee4ec4101e3d91dd5de094fd13098b540fce54918a3609864cc23e1070d3129c4efb7ca876afb4e7973ae7115269ec2719df4f594fa4b0943ecfc5e34",
          "sha256": "65cb3e92ce5250041b5509da8b77efd0dfc78e60540303c9fec38445b2e3da40",
          "sha1": "41bea3f276ab55b3361c09182ae3a855224df6bc",
          "md5": "6d4980d07b13375d22672b7eccd9492e"
        }
      ]
    }
  ]
}
