{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-create-games-contest-flow",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-create-games-contest-flow-1.0.0-alpha.aar",
          "url": "feature-create-games-contest-flow-1.0.0-alpha.aar",
          "size": 272596,
          "sha512": "f2ee954c6f366a52b6e5038c0a1f2664828b09133316449e0ee3f68d5f7ffeca7137e279e685aa308de10749c0de199b50a1f0daedf7abed84bb1ec881965ae2",
          "sha256": "f0e80b98dd08fb74825011cc2604a2ae37cb504c2dfc47afe8bc4203221649c1",
          "sha1": "f899f41820449d00873e5533ff665f8999b496b5",
          "md5": "71530ade78d1fdbbd35aa721a8a753aa"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "feature-base-contest-list-components",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-create-games-contest-flow-1.0.0-alpha.aar",
          "url": "feature-create-games-contest-flow-1.0.0-alpha.aar",
          "size": 272596,
          "sha512": "f2ee954c6f366a52b6e5038c0a1f2664828b09133316449e0ee3f68d5f7ffeca7137e279e685aa308de10749c0de199b50a1f0daedf7abed84bb1ec881965ae2",
          "sha256": "f0e80b98dd08fb74825011cc2604a2ae37cb504c2dfc47afe8bc4203221649c1",
          "sha1": "f899f41820449d00873e5533ff665f8999b496b5",
          "md5": "71530ade78d1fdbbd35aa721a8a753aa"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-create-games-contest-flow-1.0.0-alpha-sources.jar",
          "url": "feature-create-games-contest-flow-1.0.0-alpha-sources.jar",
          "size": 22163,
          "sha512": "b8c017db4c8085b73abc6b3184256dccb5514bbe75afa5f57b30489efcd0a1d6a584b1ffd6d95a316cfd24e1ca605e3add66e4e9487271d68e901e76b1b2fabf",
          "sha256": "f999d641826396c552250605b340ae8e48f9719cd7efccb01ba89f8bbd995409",
          "sha1": "985970172c4c005e90ec709004b52940247d1044",
          "md5": "3a46516d1caf6ad931b3a2893fb8ba8e"
        }
      ]
    }
  ]
}
