{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "core-model",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-model-1.0.0-alpha.aar",
          "url": "core-model-1.0.0-alpha.aar",
          "size": 233504,
          "sha512": "d446e7e6003ba82cccccfd8e35f24af8f9627ac916bcef8ada5712958782ac23825574864c984aa0efbfed023686de57a9c6a81ba6c58a59380edc70f5498f89",
          "sha256": "83c59ac2d3ae51cbf1c8970369dfd226a41ffbdefe9a5feb428367ad3847740a",
          "sha1": "e317111274719feaefe7c8d0ce92eeec798d730f",
          "md5": "0a86898bd5eee79d901e2043c0445382"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-model-1.0.0-alpha.aar",
          "url": "core-model-1.0.0-alpha.aar",
          "size": 233504,
          "sha512": "d446e7e6003ba82cccccfd8e35f24af8f9627ac916bcef8ada5712958782ac23825574864c984aa0efbfed023686de57a9c6a81ba6c58a59380edc70f5498f89",
          "sha256": "83c59ac2d3ae51cbf1c8970369dfd226a41ffbdefe9a5feb428367ad3847740a",
          "sha1": "e317111274719feaefe7c8d0ce92eeec798d730f",
          "md5": "0a86898bd5eee79d901e2043c0445382"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-model-1.0.0-alpha-sources.jar",
          "url": "core-model-1.0.0-alpha-sources.jar",
          "size": 27746,
          "sha512": "b59a25bcc651e93a29afb960692db75eb3fcc6521ce1e1f100343b1011019215ace65930dc48cab19ac00777b92519db231490ab5a2e578688ba2698a4bc5978",
          "sha256": "a14e3e104d51724e7a09674dcf60df28b30c9508379c451629f9aa5b68ad9dbc",
          "sha1": "d993e32bbc218582e29416abda891ad159ee8718",
          "md5": "53f67933f0ba63717bebce4a8535fdbc"
        }
      ]
    }
  ]
}
