npmRegistryServer: 'https://registry.npmjs.org'

npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: '${GPR_KEY}'

npmScopes:
  'lucra-sports':
    npmRegistryServer: 'https://npm.pkg.github.com'

