npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_API_TOKEN}"

npmScopes:
  "lucra-sports":
    npmRegistryServer: "https://npm.pkg.github.com"
