{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-irl-contest-details",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-irl-contest-details-1.0.0-alpha.aar",
          "url": "feature-irl-contest-details-1.0.0-alpha.aar",
          "size": 215484,
          "sha512": "f1e70a6bc5e016f98afbbff00296c8de90618af46eceb931f151d92bd54399b1b96f6a17e41d8f9ea91eda1986d29d0df5ea2dffd47aeb6cb6c2a823c76e44a7",
          "sha256": "3414e987e4e8ef533cf205cb744beccdc4249d1f392ea283d1aacf70e826bca3",
          "sha1": "5e22c034fcbdcdc02a08c9ddb1bbac26f9c38b4a",
          "md5": "2d023fd63024bfef3ca459977e35a128"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-irl-contest-details-1.0.0-alpha.aar",
          "url": "feature-irl-contest-details-1.0.0-alpha.aar",
          "size": 215484,
          "sha512": "f1e70a6bc5e016f98afbbff00296c8de90618af46eceb931f151d92bd54399b1b96f6a17e41d8f9ea91eda1986d29d0df5ea2dffd47aeb6cb6c2a823c76e44a7",
          "sha256": "3414e987e4e8ef533cf205cb744beccdc4249d1f392ea283d1aacf70e826bca3",
          "sha1": "5e22c034fcbdcdc02a08c9ddb1bbac26f9c38b4a",
          "md5": "2d023fd63024bfef3ca459977e35a128"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-irl-contest-details-1.0.0-alpha-sources.jar",
          "url": "feature-irl-contest-details-1.0.0-alpha-sources.jar",
          "size": 15077,
          "sha512": "7252f69f62e96cb81052b5e5b31abe8ced701491326bb803a2b913c1dfcf7fb879b10e64e3a2b4961a1dc33f5681d96b57f13e32fd19cefce769fb28681895b1",
          "sha256": "d024c1a92aa066f0b2e9282b6bef36c17548c33d592b126185a3630bd83832b5",
          "sha1": "25b8c0bd5449e447f924cac912a6a1a734a22e6f",
          "md5": "69e85b75449dfb3c834ed999ff36cbf7"
        }
      ]
    }
  ]
}
