{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-notification",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-notification-1.0.0-alpha.aar",
          "url": "feature-notification-1.0.0-alpha.aar",
          "size": 82962,
          "sha512": "c91e6867996e563e9465ad0b7f5a2563f4e76f556e05346f952581f53cfb16e00ead34c73823b5eb9bc8f58be1c32e9b8676ec1092ed57155267fe61b09053f4",
          "sha256": "ed56bc8e7440b46de3a07c8893211787847bf5f0d12cfcedd6ea47bbc705eda5",
          "sha1": "4db3535541f313dc830f290bb1ee933fa124dca5",
          "md5": "979db583748a933a34b8d7e2e1df37b9"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-notification-1.0.0-alpha.aar",
          "url": "feature-notification-1.0.0-alpha.aar",
          "size": 82962,
          "sha512": "c91e6867996e563e9465ad0b7f5a2563f4e76f556e05346f952581f53cfb16e00ead34c73823b5eb9bc8f58be1c32e9b8676ec1092ed57155267fe61b09053f4",
          "sha256": "ed56bc8e7440b46de3a07c8893211787847bf5f0d12cfcedd6ea47bbc705eda5",
          "sha1": "4db3535541f313dc830f290bb1ee933fa124dca5",
          "md5": "979db583748a933a34b8d7e2e1df37b9"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-notification-1.0.0-alpha-sources.jar",
          "url": "feature-notification-1.0.0-alpha-sources.jar",
          "size": 8379,
          "sha512": "5f7621b19737403d35f7b6b476430eee64f9cf3f1052d0825c31ec1fae9dd4b15284c3e9ed6f0af50e67b059f8ff169e81f551f864393bc7a6194a0b44ff61bf",
          "sha256": "3713b80dc718ff6f05e07512bd7f5dc48c4f1a4ae1dfc4a3344f8c08063e69c1",
          "sha1": "a5dba1c7e954b20642873712bb2e28094699dfd1",
          "md5": "f3b5231a880943ceb4274b5f28437965"
        }
      ]
    }
  ]
}
