{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-template-module",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-module-1.0.0-alpha.aar",
          "url": "feature-template-module-1.0.0-alpha.aar",
          "size": 38602,
          "sha512": "9cf54215dcc2ab87b778f9cf438fc6578a80c2a28d709155116c4cc9850c3b17ac214deb74435b00ac79887e5f69b5e30ab6dab2a5cd54bc520f3bdfebdd633e",
          "sha256": "9d6e315c73899199618e6b3ff095d5a9085e36215c6195af374b6d8f599b684e",
          "sha1": "8b14b2c1a89d3b28798fb176f46f57e760059dc0",
          "md5": "95d4764a3367aa1a950c3c6be3590abd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-template-module-1.0.0-alpha.aar",
          "url": "feature-template-module-1.0.0-alpha.aar",
          "size": 38602,
          "sha512": "9cf54215dcc2ab87b778f9cf438fc6578a80c2a28d709155116c4cc9850c3b17ac214deb74435b00ac79887e5f69b5e30ab6dab2a5cd54bc520f3bdfebdd633e",
          "sha256": "9d6e315c73899199618e6b3ff095d5a9085e36215c6195af374b6d8f599b684e",
          "sha1": "8b14b2c1a89d3b28798fb176f46f57e760059dc0",
          "md5": "95d4764a3367aa1a950c3c6be3590abd"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-template-module-1.0.0-alpha-sources.jar",
          "url": "feature-template-module-1.0.0-alpha-sources.jar",
          "size": 7201,
          "sha512": "b515da70ae25470c538c6880d1869a6f2f8fde21f54075693fa4121568ba74712231b6aaa467fc95f3813b0104e62fc17026ccd30a821bc159afe0154591d927",
          "sha256": "3e3f41266a440a447abf6b269dd013417f58e40e6070b3722c27e4de7b76a27a",
          "sha1": "76733fe4dacf87dc61263684c759b7e0613fe3e5",
          "md5": "9cc8de5403a128fe84acf83ab87d421f"
        }
      ]
    }
  ]
}
