{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lucrasports",
    "module": "feature-account-detail",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-detail-1.0.0-alpha.aar",
          "url": "feature-account-detail-1.0.0-alpha.aar",
          "size": 178059,
          "sha512": "10e6d85912c348eca5c307c531012ede8bcf821498bca3817c4f33c7c2880965fd3846928931b0016c2d88fa8b58934a900453186c6e0aec5345db07d353fe39",
          "sha256": "e7de7d6a9aa740e7542eceab0849704be36a3a9c7ad0c9870bdff8c07baa0ee8",
          "sha1": "ba8e5351583110f820d07654323e8e96c4998cf2",
          "md5": "f441d9eebb3dc3f7b582b1eb313c4b2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44.2"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-designsystem",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-data",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-datastore",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-common",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-navigation",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-apollo",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-auth",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-logger",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "com.lucrasports",
          "module": "core-model",
          "version": {
            "requires": "1.0.0-alpha"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "feature-account-detail-1.0.0-alpha.aar",
          "url": "feature-account-detail-1.0.0-alpha.aar",
          "size": 178059,
          "sha512": "10e6d85912c348eca5c307c531012ede8bcf821498bca3817c4f33c7c2880965fd3846928931b0016c2d88fa8b58934a900453186c6e0aec5345db07d353fe39",
          "sha256": "e7de7d6a9aa740e7542eceab0849704be36a3a9c7ad0c9870bdff8c07baa0ee8",
          "sha1": "ba8e5351583110f820d07654323e8e96c4998cf2",
          "md5": "f441d9eebb3dc3f7b582b1eb313c4b2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "feature-account-detail-1.0.0-alpha-sources.jar",
          "url": "feature-account-detail-1.0.0-alpha-sources.jar",
          "size": 15160,
          "sha512": "a0546608368ce48752d4cbc1b7bbec954e7512d271517bdbb87e3b51b0c82b93f54e35a60a05da55a65e8ba0bf2ef9827a148855d91ed265e2a48c205be0fbb8",
          "sha256": "2cc8436962f8952b1e23c09bc674eeb908ebbfa1e91faee52a6198ee61d78ffa",
          "sha1": "699a97ba3efaf8bd8f59fd74bbf7d1ceaf770993",
          "md5": "856f6b15c727c7f6e86df5544c90945a"
        }
      ]
    }
  ]
}
