name: Publish Package

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish package
        run: npm publish

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git tag -a v${PACKAGE_VERSION} -m "Version ${PACKAGE_VERSION}"
          git push --tags
